In [5]:
import numpy as np


In [16]:

arr_test=np.random.randn(3)
np.where(arr_test<0,'chikita',arr_test)

array(['chikita', 'chikita', '1.089067370851563'], dtype='<U32')

In [12]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [11]:
np.save('myarray',arr)

In [12]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [15]:
arr1=arr
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2=np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [53]:
np.savez('ziparray.npz',x=arr1,y=arr2)
archieve_array=np.load('ziparray.npz')
archieve_array['x']
archieve_array['y']


array([0, 1, 2, 3, 4])

In [71]:
np.savetxt('myfile.txt',arra)
arra=np.loadtxt('myfile.txt')
arra

array([[0., 0.],
       [1., 0.],
       [2., 0.],
       [3., 0.],
       [4., 0.],
       [5., 0.],
       [6., 0.],
       [7., 0.],
       [8., 0.],
       [9., 0.]])