In [4]:
import numpy as np
my_list1=[1,2,3,4,5]
my_list2=[11,22,33,44,55]
my_array1=np.array(my_list1)
my_array1


array([1, 2, 3, 4, 5])

In [8]:
my_lists=[my_list1, my_list2]
my_array2 = np.array(my_lists)
my_array2


array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [9]:
my_array2.dtype

dtype('int32')

In [6]:
my_zeros_array=np.zeros(5)

In [9]:
my_zeros_array

array([0., 0., 0., 0., 0.])

In [10]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])