In [2]:
import numpy as np
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
#RANDOM DISTRIBUTION
A=np.random.randn(10)
print(A)
B=np.random.randn(10)
print(B)

np.add(A,B)

[ 0.64545261  0.25778523  0.06623762  0.29207713  0.49092929 -0.34903592
  0.29635648 -0.45525994 -0.21317875 -0.13892554]
[ 0.39501791 -3.11739496  0.67878376 -0.46135305 -0.82579909  1.58332318
  1.52082612  0.9087987  -0.29832003 -0.92965616]


array([ 1.04047052, -2.85960974,  0.74502138, -0.16927592, -0.3348698 ,
        1.23428726,  1.81718261,  0.45353876, -0.51149878, -1.06858171])

In [6]:
np.maximum(A,B)

array([ 0.64545261,  0.25778523,  0.67878376,  0.29207713,  0.49092929,
        1.58332318,  1.52082612,  0.9087987 , -0.21317875, -0.13892554])

In [7]:
import webbrowser
website="https://www.udemy.com/learning-python-for-data-analysis-and-visualization/learn/v4/t/lecture/2340122?start=0"
webbrowser.open(website)

True