In [6]:
import numpy as np
print (5/2)

2.5


In [7]:
arr1=np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(arr1)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [8]:
arr1*arr1

array([[  1,   4,   9,  16,  25],
       [121, 144, 169, 196, 225]])

In [9]:
arr1/arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [11]:
arr1-1

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [12]:
arr1**3

array([[   1,    8,   27,   64,  125],
       [1331, 1728, 2197, 2744, 3375]], dtype=int32)